# These are supported funding model platforms

# Stripe github: [PrismarineTeam, AlphaKR93] custom: "https://www.buymeacoffee.com/alphakr93"
# open_collective: Prismarine # Work In Progress
patreon: alphakr93_ # Work In Progress
# issuehunt: alphakr93 # Work In Progress
ko_fi: alphakr93 # Work In Progress
custom: ["https://www.paypal.me/alphakr93", "https://toss.me/alphakr93", "https://qr.kakaopay.com/FPQhdrTiU"] #"https://toon.at/donate/637349490049950363"
# liberapay: alphakr93
